[[card]]
    name = "Flower"
    [[card.links]]
        name = "Terms of Service"
        link = "/md/terms_of_service/Flower.md"
    [[card.links]]
        name = "Privacy Policy"
        link = "/md/privacy_policy/Flower.md"
