[[card]]
    name = "Flower"
    [[card.links]]
        name = "Terms of Service"
        link = "/static/docs/terms_of_service/Flower.md"
    [[card.links]]
        name = "Privacy Policy"
        link = "/static/docs/privacy_policy/Flower.md"
