[[card]]
    name = "Honey"
    [[card.links]]
        name = "Terms of Service"
        link = "/static/docs/terms_of_service/Honey.md"
    [[card.links]]
        name = "Privacy Policy"
        link = "/static/docs/privacy_policy/Honey.md"
