[[card]]
    name = "MarriageBot"
    [[card.links]]
        name = "Terms of Service"
        link = "/static/docs/terms_of_service/MarriageBot.md"
    [[card.links]]
        name = "Privacy Policy"
        link = "/static/docs/privacy_policy/MarriageBot.md"
