website_base_url = "http://localhost:8080"
login_url = "/login"
routes = [
    "frontend",
    "backend",
    "stripe",
    "paypal",
    "upgradechat",
    "logins",
    "cancel_subscription",
    "payment_portal",
    "payment_portal_api",
]
stripe_api_key = ""
stripe_webhook_signing_secret = ""

# Used for the bot's invite and login links
[oauth.discord]
    client_id = ""
    client_secret = ""
[oauth.google]
    client_id = ""
    client_secret = ""
[oauth.everlasting]
    api_key = ""


[database]
    enabled = true
    user = ""
    password = ""
    database = ""
    host = ""
    port = 5432


[redis]
    enabled = false
    host = "127.0.0.1"
    port = 6379
    db = 0
