website_base_url = "http://localhost:8080"
login_url = "/login"
routes = [
    "frontend",
    "backend",
    "stripe",
    "paypal",
    "checkout_items",
    "cancel_subscription",
    "payment_portal",
]
oauth_scopes = [
    "identify",
]

stripe_api_key = ""
stripe_webhook_signing_secret = ""
paypal_client_id = ""
paypal_client_secret = ""

# Used for the bot's invite and login links
[oauth]
    client_id = ""
    client_secret = ""

# This data is passed directly over to asyncpg.connect()
[database]
    enabled = true
    user = ""
    password = ""
    database = ""
    host = ""
    port = 5432

# This data is passed directly over to aioredis.connect()
[redis]
    enabled = false
    host = "127.0.0.1"
    port = 6379
    db = 0
